name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    env:
      TERM: xterm-256color
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Bats testing framework
      uses: mig4/setup-bats@v1

    - name: Clone testing library
      run: git clone https://github.com/Yandex-Practicum/tests-middle-frontend.git /tmp/tests-middle-frontend

    - name: Run sprint_1 tests
      run: bats --formatter pretty /tmp/tests-middle-frontend/tests/sprint_1.bats

    - name: Run sprint_2 tests
      run: bats --formatter pretty /tmp/tests-middle-frontend/tests/sprint_2.bats

    - name: Run sprint_3 tests
      run: bats --formatter pretty /tmp/tests-middle-frontend/tests/sprint_3.bats

    - name: Run sprint_4 tests
      run: bats --formatter pretty /tmp/tests-middle-frontend/tests/sprint_4.bats

    - name: Run server tests
      run: bats --formatter pretty /tmp/tests-middle-frontend/tests/node_build.bats





